# Generated by Django 5.0.1 on 2024-01-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=200)),
                ('mob_num', models.IntegerField(max_length=10)),
                ('email_id', models.CharField(max_length=50)),
                ('message', models.TextField()),
            ],
        ),
    ]
